config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'menus#index'
  resources :users, only: [:show]
  resources :standards, only: :index
  resources :intakes, only: :index
  resources :menus do
    resources :standards, except: :index
    resources :intakes, except: :index
    collection do
      get 'search'
    end
  end
  resources :graphs, only: :create
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :standards, dependent: :destroy
  has_many :intakes, dependent: :destroy
  has_many_attached :images

  with_options presence: true do
    validates :title
    validates :amount
    validates :unit
    validates :calorie
  end

  with_options numericality: { greater_than: 0 } do
    validates :amount
    validates :calorie
  end

  validate :images_five?
  validates :bar_code, format: { with: /\A[0-9]*\z/, message: 'は0から9の数字のみで入力してください' }

  def self.search(word)
    if word != ''
      Menu.where('title LIKE(?)', "%#{word}%")
    else
      Menu.all
    end
  end

  def self.menu_list(menu)
    menu_ary = []
    menu_hash = {}

    menu_hash[:value] = menu.amount / 3
    menu_hash[:calorie] = menu.calorie / 3
    menu_ary << menu_hash
    menu_hash = {}

    menu_hash[:value] = menu.amount / 2
    menu_hash[:calorie] = menu.calorie / 2
    menu_ary << menu_hash
    menu_hash = {}

    menu_hash[:value] = menu.amount
    menu_hash[:calorie] = menu.calorie
    menu_ary << menu_hash
    menu_hash = {}

    menu_hash[:value] = menu.amount * 2
    menu_hash[:calorie] = menu.calorie * 2
    menu_ary << menu_hash
    menu_hash = {}

    menu_hash[:value] = menu.amount * 3
    menu_hash[:calorie] = menu.calorie * 3
    menu_ary << menu_hash

    menu_ary
  end

  private

  def images_five?
    errors.add(:images, 'は5枚添付してください') if images.length != 5
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: [:show, :edit, :update, :destroy]

  def index
    @menus = Menu.all.order('created_at DESC')
  end

  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.new(menu_params)
    if @menu.valid?
      Menu.create(menu_params)
    else
      render :new
    end
  end

  def show
    @menu_list = Menu.menu_list(@menu)
  end

  def edit
  end

  def update
    render :edit unless @menu.update(menu_params)
  end

  def destroy
    @menu.destroy
  end

  def search
    @menus = Menu.search(params[:keyword])
  end

  private

  def menu_params
    params.require(:menu).permit(:title, :amount, :unit, :calorie, :bar_code, images: [])
  end

  def set_menu
    @menu = Menu.find(params[:id])
  end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/create.html.erb
<%= render "shared/header"%>
<div class="container-fluid">
  <div class="row">
    <%= render "shared/nav-bar"%>
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <%= render "shared/menus_header" %>
      <%# メイン画面の内容部分 %>
      <div><%= @menu.title %>が新規登録されました。続けて登録しますか？</div>
      <div class="col-sm-auto col-md-3 my-3">
        <div><%= link_to '登録する', new_menu_path, class: "btn btn-secondary" %></div>
        <div class="my-3"><%= link_to '食事メニューへ戻る', menus_path, class: "btn btn-success" %></div>
      </div>
      <%# //メイン画面の内容部分 %>
    </main>
  </div>
</div>
<%= render "shared/footer"%>

app/views/menus/destroy.html.erb
<%= render "shared/header"%>
<div class="container-fluid">
  <div class="row">
    <%= render "shared/nav-bar"%>
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <%= render "shared/menus_header" %>
      <%# メイン画面の内容部分 %>
      <div><%= @menu.title %>が削除されました。</div>
      <%= link_to '食事メニューへ戻る', menus_path, class: "btn btn-success my-3" %>
      <%# //メイン画面の内容部分 %>
    </main>
  </div>
</div>
<%= render "shared/footer"%>

app/views/menus/edit.html.erb
<%= render "shared/header"%>
<div class="container-fluid">
  <div class="row">
    <%= render "shared/nav-bar"%>
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <%= render "shared/menus_header" %>
      <%# メイン画面の内容部分 %>
      <%= render "shared/menu_form"%>
      <%# //メイン画面の内容部分 %>
    </main>
  </div>
</div>
<%= render "shared/footer"%>

app/views/menus/index.html.erb
<%= render "shared/header"%>
  <div class="container-fluid">
    <div class="row">
      <%= render "shared/nav-bar"%>
      <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <%= render "shared/menus_header" %>
        <%# メイン画面の内容部分 %>
        <%= render "shared/menu_list" %>
        <h2>メニュー表</h2>
        <div class="table-responsive">
          <table class="table table-sm">
            <thead>
              <tr>
                <th>メニュー名</th>
                <th>分量</th>
                <th>カロリー</th>
              </tr>
            </thead>
            <tbody>
            <% @menus.each do |menu| %>
              <tr>
                <td><%= link_to menu.title, menu_path(menu.id), class:"link-text-color td-none" %></td>
                <td><%= menu.amount %> <%= menu.unit %></td>
                <td><%= menu.calorie %> kcal</td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
        <%# //メイン画面の内容部分 %>
      </main>
    </div>
  </div>
<%= render "shared/footer"%>

app/views/menus/new.html.erb
<%= render "shared/header"%>
<div class="container-fluid">
  <div class="row">
    <%= render "shared/nav-bar"%>
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <%= render "shared/menus_header" %>
      <%# メイン画面の内容部分 %>
      <%= render "shared/menu_form"%>
      <%# //メイン画面の内容部分 %>
    </main>
  </div>
</div>
<%= render "shared/footer"%>

app/views/menus/search.html.erb
<%= render "shared/header"%>
  <div class="container-fluid">
    <div class="row">
      <%= render "shared/nav-bar"%>
      <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <%= render "shared/menus_header" %>
        <%# メイン画面の内容部分 %>
        <%= render "shared/menu_list" %>
        <%# //メイン画面の内容部分 %>
      </main>
    </div>
  </div>
<%= render "shared/footer"%>

app/views/menus/show.html.erb
<%= render "shared/header"%>
<div class="container-fluid">
  <div class="row">
    <%= render "shared/nav-bar"%>
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <%= render "shared/menus_header" %>
      <%# メイン画面の内容部分 %>
      <div class="container-fluid">
        <p class="fs-3 mx-auto p-3" style="width: 200px;"><%= @menu.title %></p>
        <div class="menu-list">
          <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-5 g-3">
            <% @menu.images.each do |image|%>
              <%= image_tag image.variant(resize_to_fill:[150, 150]), class:'images' %>
            <% end %>
          </div>
          <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-5 gx-3 my-3">
            <% i = 4 %>
            <% 5.times do %>
              <div class="col d-flex justify-content-around">
                <%= @menu_list[i][:calorie] %> kcal (<%= @menu_list[i][:value] %> <%= @menu.unit %>)
              </div>
              <% i -= 1 %>
            <% end %>
          </div>
        </div>
        <div>
          <%# 基準がまだ登録されていない場合に表示 %>
          <% if Standard.where(user_id: current_user.id, menu_id: @menu.id) == []%>
          <%= link_to '基準登録(推奨)', new_menu_standard_path(@menu.id), class: "btn btn-lg btn-warning fs-3" %>
          <% end %>
          <%# /基準がまだ登録されていない場合に表示 %>
          <%= link_to '実績登録', new_menu_intake_path(@menu.id), class: "btn btn-lg btn-info fs-3 " %>
        </div>
        <div class="row row-cols-1 row-cols-sm-2 g-0">
          <div class="col justify-content-between align-items-center">
            <div class="btn-group my-3">
              <%= link_to '削除', menu_path(@menu.id), method: :delete, class: "btn btn-sm btn-outline-light" %>
              <%= link_to '編集', edit_menu_path(@menu.id), class: "btn btn-sm btn-outline-light" %>
            </div>
          </div>
        </div>
      </div>
    </main>
  </div>
</div>
<%= render "shared/footer"%>

app/views/menus/update.html.erb
<%= render "shared/header"%>
<div class="container-fluid">
  <div class="row">
    <%= render "shared/nav-bar"%>
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <%= render "shared/menus_header" %>
      <%# メイン画面の内容部分 %>
      <div><%= @menu.title%>の内容が更新されました。</div>
      <%= link_to '食事メニューへ戻る', menus_path, class: "btn btn-success my-3" %>
      <%# //メイン画面の内容部分 %>
    </main>
  </div>
</div>
<%= render "shared/footer"%>