config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'menus#index'
  resources :users, only: [:show]
  resources :standards, only: :index
  resources :intakes, only: :index
  resources :menus do
    resources :standards, except: :index
    resources :intakes, except: :index
    collection do
      get 'search'
    end
  end
  resources :graphs, only: :create
end

app/views/shared/_footer.html.erb
<footer class="footer bg-dark">
  <div class="container d-flex justify-content-center">
    <span class="text-muted">
      <a class="navbar-brand" href="/">
      <i class="bi bi-globe2" style="font-size: 2rem; color: cornflowerblue;">Fokus</i>
      </a>
    </span>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="/">
    <i class="bi bi-globe2" style="font-size: 2rem; color: cornflowerblue;">Fokus</i>
  </a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <%# 全画面では表示されない %>
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= form_with(url: search_menus_path, local: true, method: :get, class: "w-100 bg-dark") do |f| %>
    <div class="w-100 d-flex ">
      <%= f.label :keyword, class: "visually-hidden" %>
      <%= f.text_field :keyword, placeholder: '検索したいメニュー名を入力してください', class: "w-100 bg-dark text-white" %>
      <%= f.submit '検索', class: "btn btn-outline-light"%>
    </div>
  <% end %>
  <ul class="navbar-nav-row px-3">
    <% if user_signed_in? %>
    <li class="nav-item text-nowrap">
    <%= link_to "#{current_user.nickname}", user_path(current_user.id), class: 'nav-link btn btn-sm btn-outline-light mx-3' %>
    </li>
    <li class="nav-item text-nowrap">
    <%= link_to 'ログアウト', destroy_user_session_path, class: 'nav-link btn btn-sm btn-outline-light mx-3', method: :delete %>
    </li>
    <% else %>
    <li class="nav-item text-nowrap">
    <%= link_to '新規登録', new_user_registration_path, class: 'nav-link btn btn-sm btn-outline-light' %>
    </li>
    <li class="nav-item text-nowrap">
    <%= link_to 'ログイン', new_user_session_path, class: 'nav-link btn btn-sm btn-outline-light' %>
    </li>
    <% end %>
  </ul>
</header>

app/views/shared/_intakes_header.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2 text-info">実績モード</h1>
</div>

app/views/shared/_menu_form.erb
<%= form_with model: @menu, local: true, class:"row g-3" do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  <div>
    <div class="col-12">
      <%= f.label :title %>
    </div>
    <div class="col-12">
      <%= f.text_field :title, placeholder: '例）ハンバーグ', autofocus: true %>
    </div>
  </div>
  <div>
    <div class="col-12">
      <%= f.label :amount %>
    </div>
    <div class="col-12">
      <%= f.text_field :amount, placeholder: '例）300' %>
    </div>
  </div>
  <div>
    <div class="col-12">
      <%= f.label :unit %>
    </div>
    <div class="col-12">
      <%= f.text_field :unit, placeholder: '例）個, g, mL ' %>
    </div>
  </div>
  <div>
    <div>
      <%= f.label :calorie %>
    </div>
    <div class="col-12">
      <%= f.text_field :calorie, placeholder: '例）450' %>kcal
    </div>
  </div>
  <div>
    <div>
      <%= f.label :bar_code %>
    </div>
    <div class="col-12">
      <%= f.text_field :bar_code, placeholder: '例）0123456789' %>
    </div>
  </div>
  <div class="image-selects">
    <p>※画像は分量が多い順に5枚添付してください<br>(特大→大→中→小→ミニ)</p>
    <%= f.label :images %>
    <%= f.file_field :images, name: 'menu[images][]', id:"menu-image" %>
  </div>
  <%# JavaScriptによる画像挿入用要素 %>
  <div id="image-list"></div>
  <div class="d-grid gap-2 col-6 my-4">
    <%= f.submit '登録する', class:"btn btn-primary btn-lg" %>
  </div>
<% end %>

app/views/shared/_menu_list.html.erb
<div class="my-4 w-100" id="myChart" width="900" height="380">
  <div class="album py-5">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <% @menus.each do |menu| %>
        <div class="col">
          <div class="card shadow-sm">
            <%= link_to image_tag(menu.images[2].variant(resize_to_fill:[250, 250])), menu_path(menu.id), class: "d-flex justify-content-center" %>
            <div class="card-title">
              <%= link_to menu.title, menu_path(menu.id), class: "d-flex justify-content-center link-text td-none" %>
              <div class="d-flex justify-content-around align-items-center">
                <div class="btn-group">
                  <%= link_to '実績登録', new_menu_intake_path(menu.id), class: "btn btn-sm btn-outline-info" %>
                  <% if Standard.where(user_id: current_user.id, menu_id: menu.id) == []%>
                    <%= link_to '基準登録', new_menu_standard_path(menu.id), class: "btn btn-sm btn-outline-warning" %>
                  <% end %>
                </div>
                <small>
                  <%= menu.calorie %> kcal
                </small>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_menus_header.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2 text-green">メニューモード</h1>
  <div class="btn-toolbar mb-2 mb-md-0">
    <%= link_to '新メニュー作成（開発者用）', new_menu_path, class:"btn btn-success p-2" %>
  </div>
</div>

app/views/shared/_nav-bar.html.erb
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block sidebar collapse">
  <div class="position-sticky pt-3">
    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
    <span>カロリー摂取系</span>
    </h6>
    <ul class="nav flex-column">
      <li class="nav-item">
        <%= link_to '食事メニュー', menus_path, class: "nav-link btn btn-success btn-lg my-1", 'aria-current': "page" %>
          <span data-feather="home"></span>
      </li>
      <li class="nav-item">
        <%= link_to "食事基準", standards_path, class: "nav-link btn btn-warning btn-lg my-1" %>
          <span data-feather="file"></span>
      </li>
      <li class="nav-item">
        <%= link_to "食事実績", intakes_path, class: "nav-link btn btn-info btn-lg my-1" %>
          <span data-feather="shopping-cart"></span>
      </li>
    </ul>

    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
      <span>カロリー消費系</span>
      <a class="link-secondary" href="#" aria-label="Add a new report">
        <span data-feather="plus-circle"></span>
      </a>
    </h6>
    <ul class="nav flex-column mb-2">
      <li class="nav-item">
        <a class="nav-link btn btn-outline-success btn-lg my-1" href="#">
          <span data-feather="file-text"></span>
          運動メニュー(準備中)
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link nav-link btn btn-outline-warning btn-lg my-1" href="#">
          <span data-feather="file-text"></span>
          運動基準(準備中)
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link nav-link btn btn-outline-info btn-lg my-1" href="#">
          <span data-feather="file-text"></span>
          運動実績(準備中)
        </a>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_standard_form.erb
<%= form_with model: [@menu, @standard], local: true, class:"row my-3" do |f| %>
<%= render 'layouts/error_messages', model: f.object %>
<div class="row my-3 fs-4">
  <div class="col-12 d-flex justify-content-center align-items-center fs-6">
  <%= f.label :large, class:"fw-bol text-warning" %>だと感じる量を選択してください
  </div>
  <% i = 4 %>
  <% while i >= 0 do %>
    <div class="col d-flex justify-content-center align-items-center">
    <label><%= f.radio_button :large, :"#{@amount_cal[i]}", class:"form-check-input" %> <%= @amount_cal[i] %> <%= @menu.unit %></label>
    </div>
  <% i -= 1 %>
  <% end %>
</div>
<div class="row my-3 fs-4">
  <div class="col-12 d-flex justify-content-center fs-6">
  <%= f.label :medium, class:"fw-bol text-warning" %>だと感じる量を選択してください
  </div>
  <% i = 4 %>
  <% while i >= 0 do %>
    <div class="col d-flex justify-content-center align-items-center">
    <label><%= f.radio_button :medium, :"#{@amount_cal[i]}", class:"form-check-input" %> <%= @amount_cal[i] %> <%= @menu.unit %></label>
    </div>
  <% i -= 1 %>
  <% end %>
</div>
<div class="row my-3 fs-4">
  <div class="col-12 d-flex justify-content-center fs-6">
  <%= f.label :small, class:"fw-bol text-warning" %>だと感じる量を選択してください
  </div>
  <% i = 4 %>
  <% while i >= 0 do %>
    <div class="col d-flex justify-content-center align-items-center">
    <label><%= f.radio_button :small, :"#{@amount_cal[i]}", class:"form-check-input" %> <%= @amount_cal[i] %> <%= @menu.unit %></label>
    </div>
  <% i -= 1 %>
  <% end %>
</div>
<div class="d-grid gap-2 col-6 mx-auto my-4">
  <%= f.submit '登録する', class:"btn btn-primary btn-lg" %>
</div>
<% end %>

app/views/shared/_standards_header.html copy.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2">基準モード</h1>
  <div class="btn-toolbar mb-2 mb-md-0">
    <div class="btn-group me-2">
      <button type="button" class="btn btn-sm btn-outline-secondary">
      <%= link_to '新メニュー作成（開発者用）', new_menu_path %>
      </button>
      <button type="button" class="btn btn-sm btn-outline-secondary">
      Export
      </button>
    </div>
    <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
      <span data-feather="calendar"></span>
      This week
    </button>
  </div>
</div>

app/views/shared/_standards_header.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2 text-warning">基準モード</h1>
</div>