config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'menus#index'
  resources :users, only: [:show]
  resources :standards, only: :index
  resources :intakes, only: :index
  resources :menus do
    resources :standards, except: :index
    resources :intakes, except: :index
    collection do
      get 'search'
    end
  end
  resources :graphs, only: :create
end

app/models/standard.rb
class Standard < ApplicationRecord
  belongs_to :user
  belongs_to :menu

  with_options numericality: { greater_than: 0, message: 'を選択してください' } do
    validates :large
    validates :medium
    validates :small
  end

  def self.calorie_cal(targets)
    stn_ary = []
    if targets[0].nil?
      ary = []
      ary << targets
      targets = ary
    end
    targets.each do |standard|
      stn_hash = {}

      menu_cal = standard.menu.calorie
      menu_amount = standard.menu.amount
      stn_large = standard.large
      stn_medium = standard.medium
      stn_small = standard.small

      large_cal = menu_cal * stn_large / menu_amount
      medium_cal = menu_cal * stn_medium / menu_amount
      small_cal = menu_cal * stn_small / menu_amount

      stn_hash[:id] = standard.id
      stn_hash[:menu_id] = standard.menu_id
      stn_hash[:title] = standard.menu.title
      stn_hash[:large_amount] = stn_large
      stn_hash[:medium_amount] = stn_medium
      stn_hash[:small_amount] = stn_small
      stn_hash[:unit] = standard.menu.unit
      stn_hash[:large_cal] = large_cal
      stn_hash[:medium_cal] = medium_cal
      stn_hash[:small_cal] = small_cal
      stn_ary << stn_hash
    end
    stn_ary
  end

  def self.amount_cal(menu)
    amount_ary = []
    value1 = menu.amount / 3
    value2 = menu.amount / 2
    value3 = menu.amount
    value4 = menu.amount * 2
    value5 = menu.amount * 3

    amount_ary << value1
    amount_ary << value2
    amount_ary << value3
    amount_ary << value4
    amount_ary << value5
  end
end

app/controllers/standards_controller.rb
class StandardsController < ApplicationController
  before_action :set_standard, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, only: [:show, :edit, :update, :destroy]

  def index
    @standards = Standard.includes(:menu).where(user_id: current_user.id).order('created_at DESC')
    @menus = Menu.all
    @cal_results = Standard.calorie_cal(@standards) unless @standards == []
  end

  def new
    @standard = Standard.new
    set_menu
    @amount_cal = Standard.amount_cal(@menu)
  end

  def create
    if params[:standard].nil?
      redirect_to new_menu_standard_path
    else
      @standard = Standard.new(standard_params)
      if @standard.valid?
        Standard.create(standard_params)
      else
        set_menu
        @amount_cal = Standard.amount_cal(@menu)
        render :new
      end
    end
  end

  def show
    @cal_result = Standard.calorie_cal(@standard)
  end

  def edit
    @menu = @standard.menu
    @amount_cal = Standard.amount_cal(@menu)
  end

  def update
    return if @standard.update(standard_params)

    @menu = @standard.menu
    render :edit
  end

  def destroy
    @standard.destroy
  end

  private

  def standard_params
    params.require(:standard).permit(:large, :medium, :small).merge(user_id: current_user.id, menu_id: params[:menu_id])
  end

  def set_menu
    @menu = Menu.find(params[:menu_id])
  end

  def set_standard
    @standard = Standard.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless @standard.user_id == current_user.id
  end
end

app/helpers/standards_helper.rb
module StandardsHelper
end

app/views/standards/create.html.erb
<%= render "shared/header"%>
<div class="container-fluid">
  <div class="row">
    <%= render "shared/nav-bar"%>
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <%= render "shared/standards_header" %>
      <%# メイン画面の内容部分 %>
      <div><%= @standard.menu.title %>の基準が新規登録されました。</div>
      <div class="col-sm-auto col-md-3 my-3">
        <div><%= link_to '食事メニュー', menus_path, class: "btn btn-success my-3" %></div>
        <div><%= link_to '食事基準', standards_path, class: "btn btn-warning my-3" %></div>
        <div><%= link_to "#{@standard.menu.title}の食事実績を登録する", new_menu_intake_path(@standard.menu), class: "btn btn-info my-3" %></div>
      <%# //メイン画面の内容部分 %>
    </main>
  </div>
</div>
<%= render "shared/footer"%>

app/views/standards/destroy.html.erb
<%= render "shared/header"%>
<div class="container-fluid">
  <div class="row">
    <%= render "shared/nav-bar"%>
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <%= render "shared/standards_header" %>
      <%# メイン画面の内容部分 %>
      <div><%= @standard.menu.title %>の基準が削除されました。</div>
      <div><%= link_to '食事基準へ戻る', standards_path, class: "btn btn-warning my-3" %></div>
      <%# //メイン画面の内容部分 %>
    </main>
  </div>
</div>
<%= render "shared/footer"%>

app/views/standards/edit.html.erb
<%= render "shared/header"%>
<div class="container-fluid">
  <div class="row">
  <%= render "shared/nav-bar"%>
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <%= render "shared/standards_header" %>
      <%# メイン画面の内容部分 %>
      <div class="container-fluid">
        <p class="fs-3 mx-auto p-3 text-center"><%= @menu.title %></p>
        <div class="menu-list">
          <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-5 g-3">
          <% @menu.images.each do |image|%>
            <%= image_tag image.variant(resize_to_fill:[150, 150]), class:'images' %>
          <% end %>
          </div>
          <%= render 'shared/standard_form' %>
        </div>
      </div>
    </main>
  </div>
</div>
<%= render "shared/footer"%>

app/views/standards/index.html.erb
<%= render "shared/header"%>
  <div class="container-fluid">
    <div class="row">
      <%= render "shared/nav-bar"%>
      <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <%= render "shared/standards_header" %>
        <h2>メニュー表</h2>
        <div class="table-responsive">
          <table class="table table-sm">
            <thead>
              <tr>
                <th>操作ボタン</th>
                <th>メニュー名</th>
                <th>多め</th>
                <th>普通</th>
                <th>少なめ</th>
              </tr>
            </thead>
            <tbody>
            <% unless @standards == []%>
              <% @cal_results.each do |result| %>
                <tr>
                  <td>
                    <div class="btn-group">
                    <%= link_to '削除', menu_standard_path(result[:menu_id], result[:id]), method: :delete, class: "btn btn-sm btn-outline-light" %>
                    <%= link_to '編集', edit_menu_standard_path(result[:menu_id], result[:id]), class: "btn btn-sm btn-outline-light" %>
                    </div>
                  </td>
                  <td>
                    <%= link_to result[:title], menu_standard_path(result[:menu_id], result[:id]), class:"link-text-color td-none" %>
                  </td>
                  <td>
                    <%= "#{result[:large_amount]}(#{result[:unit]})"%>
                    <%= result[:large_cal] %>kcal
                  </td>
                  <td>
                    <%= "#{result[:medium_amount]}(#{result[:unit]})"%>
                    <%= result[:medium_cal] %>kcal
                  </td>
                  <td>
                    <%= "#{result[:small_amount]}(#{result[:unit]})"%>
                    <%= result[:small_cal] %>kcal
                  </td>
                </tr>
              <% end %>
            <% end %>
            </tbody>
          </table>
        </div>
      </main>
    </div>
  </div>
<%= render "shared/footer"%>

app/views/standards/new.html.erb
<%= render "shared/header"%>
<div class="container-fluid">
  <div class="row">
  <%= render "shared/nav-bar"%>
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <%= render "shared/standards_header" %>
      <%# メイン画面の内容部分 %>
      <div class="container-fluid"> 
        <p class="fs-3 mx-auto p-3 text-center"><%= @menu.title %></p>
        <div class="menu-list">
          <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-5 g-3">
          <% @menu.images.each do |image|%>
            <%= image_tag image.variant(resize_to_fill:[150, 150]), class:'images' %>
          <% end %>
          </div>
          <% unless Standard.where(user_id: current_user.id, menu_id: @menu.id) == [] %>
            <div>
              すでに基準が登録されています
            </div>
          <% else %>
            <%= render 'shared/standard_form'%>
          <% end %>
        </div>
      </div>
    </main>
  </div>
</div>
<%= render "shared/footer"%>

app/views/standards/show.html.erb
<%= render "shared/header"%>
  <div class="container-fluid">
    <div class="row">
      <%= render "shared/nav-bar"%>
      <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <%= render "shared/standards_header" %>
        <h2><%= @standard.menu.title %>の基準</h2>
        <div class="table-responsive">
          <table class="table table-sm">
            <thead>
              <tr>
                <th>メニュー名</th>
                <th>多め</th>
                <th>普通</th>
                <th>少なめ</th>
                <th>その他</th>
              </tr>
            </thead>
            <tbody>
            <% @cal_result.each do |result| %>
              <tr>
                <td>
                  <%= result[:title] %>
                </td>
                <td>
                  <%= "#{result[:large_amount]}(#{result[:unit]})"%>
                  <%= result[:large_cal] %>kcal
                </td>
                <td>
                  <%= "#{result[:medium_amount]}(#{result[:unit]})"%>
                  <%= result[:medium_cal] %>kcal
                </td>
                <td>
                  <%= "#{result[:small_amount]}(#{result[:unit]})"%>
                  <%= result[:small_cal] %>kcal
                </td>
                <td>other</td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
        <div class="row row-cols-1 row-cols-sm-2 g-0">
          <div class="col justify-content-between align-items-center">
            <div class="btn-group">
              <%= link_to '削除', menu_standard_path(@standard.menu_id, @standard.id), method: :delete, class: "btn btn-sm btn-outline-light" %>
              <%= link_to '編集', edit_menu_standard_path(@standard.menu_id, @standard.id), class: "btn btn-sm btn-outline-light" %>
            </div>
          </div>
        </div>
      </main>
    </div>
  </div>
<%= render "shared/footer"%>

app/views/standards/update.html.erb
<%= render "shared/header"%>
<div class="container-fluid">
  <div class="row">
    <%= render "shared/nav-bar"%>
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <%= render "shared/standards_header" %>
      <%# メイン画面の内容部分 %>
      <div><%= @standard.menu.title %>の基準が更新されました。</div>
      <div class="col-sm-auto col-md-3 my-3">
        <div><%= link_to '食事基準へ戻る', standards_path, class: "btn btn-warning my-3" %></div>
        <div><%= link_to "#{@standard.menu.title}の食事実績を登録する", new_menu_intake_path(@standard.menu), class: "btn btn-info my-3" %></div>
      </div>
      <%# //メイン画面の内容部分 %>
    </main>
  </div>
</div>
<%= render "shared/footer"%>