config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'menus#index'
  resources :users, only: [:show]
  resources :standards, only: :index
  resources :intakes, only: :index
  resources :menus do
    resources :standards, except: :index
    resources :intakes, except: :index
    collection do
      get 'search'
    end
  end
  resources :graphs, only: :create
end

app/models/intake.rb
class Intake < ApplicationRecord
  belongs_to :user
  belongs_to :menu

  extend ActiveHash::Associations::ActiveRecordExtensions

  belongs_to :value
  belongs_to :timing

  validates :date, presence: true

  with_options numericality: { other_than: 1, message: 'を選択してください' } do
    validates :timing_id
    validates :value_id
  end
end

app/controllers/intakes_controller.rb
class IntakesController < ApplicationController
  before_action :set_intake, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, only: [:show, :edit, :update, :destroy]

  def index
    @intakes = Intake.includes(:menu).where(user_id: current_user.id).order('date DESC').order('timing_id DESC')
    set_standards
    Graph.destroy_graph(Graph.all)
  end

  def new
    @intake = Intake.new
    set_menu
  end

  def create
    @intake = Intake.new(intake_params)
    return @menus = Menu.all.order('created_at DESC') if @intake.save

    set_menu
    render :new
  end

  def show
    set_standards
  end

  def edit
    @menu = @intake.menu
  end

  def update
    return if @intake.update(intake_params)

    @menu = @intake.menu
    render :edit
  end

  def destroy
    @intake.destroy
  end

  private

  def intake_params
    params.require(:intake).permit(
      :date, :timing_id, :value_id
    ).merge(user_id: current_user.id, menu_id: params[:menu_id])
  end

  def set_menu
    @menu = Menu.find(params[:menu_id])
  end

  def set_intake
    @intake = Intake.find(params[:id])
  end

  def set_standards
    @standards = Standard.includes(:menu).where(user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless @intake.user_id == current_user.id
  end
end

app/helpers/intakes_helper.rb
module IntakesHelper
end

app/views/intakes/create.html.erb
<%= render "shared/header"%>
<div class="container-fluid">
  <div class="row">
    <%= render "shared/nav-bar"%>
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <%= render "shared/intakes_header" %>
      <%# メイン画面の内容部分 %>
      <div><%= @intake.menu.title %>の食事実績が登録されました。</div>
      <div class="my-3">画像をクリックして他のメニューも登録しましょう！</div>
      <div class="container">
        <div class="row row-cols-3 row-cols-sm-4 row-cols-md-5 g-3">
          <% @menus.each do |menu| %>
          <div class="col">
            <div class="card shadow-sm">
              <%= link_to image_tag(menu.images[2].variant(resize_to_fill:[100, 100])), new_menu_intake_path(menu.id), class: "d-flex justify-content-center" %>
              <div class="card-title">
                <%= link_to menu.title, new_menu_intake_path(menu.id), class: "d-flex justify-content-center link-text td-none" %>
                <div class="d-flex justify-content-around align-items-center">
                  <small>
                    <%= menu.calorie %> kcal (<%= menu.amount %> <%= menu.unit %>)
                  </small>
                </div>
              </div>
            </div>
          </div>
          <% end %>
        </div>
      </div>
      <div><%= link_to '食事メニューへ', menus_path, class: "btn btn-success" %></div>
    </main>
  </div>
</div>
<%= render "shared/footer"%>

app/views/intakes/destroy.html.erb
<%= render "shared/header"%>
<div class="container-fluid">
  <div class="row">
    <%= render "shared/nav-bar"%>
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <%= render "shared/intakes_header" %>
      <%# メイン画面の内容部分 %>
      <div><%= @intake.menu.title %>の食事実績が削除されました。</div>
      <div><%= link_to '食事実績へ戻る', intakes_path, class: "btn btn-info my-3" %></div>
    </main>
  </div>
</div>
<%= render "shared/footer"%>

app/views/intakes/edit.html.erb
<%= render "shared/header"%>
<div class="container-fluid">
  <div class="row">
    <%= render "shared/nav-bar"%>
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <%= render "shared/intakes_header" %>
      <%# メイン画面の内容部分 %>
      <h2><%= @menu.title%>の食事実績編集</h2>
      <%= form_with model: [@menu, @intake], local: true, class:"row my-3" do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
        <div class="row my-3 fs-5">
          <div class="col-12">
            <%= f.label :date %>
          </div>
          <div class="col">
            <%= f.date_select :date, start_year: 2021, end_year: 2021 %>
          </div>
        </div>
        <div class="row my-3 fs-5">
          <div class="col-12">        
            <%= f.label :timing_id %>
          </div>
          <div class="col">
            <%= f.collection_select(:timing_id, Timing.all, :id, :name, {}, {}) %>
          </div>
        </div>
        <div class="row my-3 fs-5">
          <div class="col-12">    
            <%= f.label :value_id %>
          </div>
          <div class="col">
            <%= f.collection_select(:value_id, Value.all, :id, :name, {}, {}) %>
          </div>
        </div>
        <div class="d-grid gap-2 col-6 my-4">
          <%= f.submit '修正する', class:"btn btn-primary btn-lg" %>
        </div>
      <% end %>
    </main>
  </div>
</div>
<%= render "shared/footer"%>

app/views/intakes/index.html.erb
<%= render "shared/header"%>

<div class="container-fluid">
  <div class="row">

    <%= render "shared/nav-bar"%>
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">

    <%= render "shared/intakes_header" %>
    <%# メイン画面の内容部分 %>
      <%# グラフ表示 %>
      <div>
      <%= column_chart Graph.group(:date).sum(:calorie), colors: ["coral"], xtitle: "日付", ytitle: "kcal", stacked: true, suffix: " kcal", thousands: ",", empty: "グラフ作成ボタンを押してください" %>
        <% if Graph.all == [] %>
        <div class="d-flex justify-content-center col my-4">
          <%= link_to 'グラフ作成', graphs_path, method: :post, class: "btn btn-sm btn-primary btn-lg fs-3 w-50" %>
        </div>
        <% end %>
      </div>
      <%# //グラフ表示 %>        
      <h2>食事実績</h2>
      <div class="table-responsive">
        <table class="table table-sm">
          <thead>
            <tr>
              <th>操作ボタン</th>
              <th>日付</th>
              <th>時間帯</th>
              <th>メニュー名</th>
              <th>感覚量</th>
              <th>分量</th>
              <th>カロリー</th>
              <th>other</th>
            </tr>
          </thead>
          <tbody>
          <% @intakes.each do |intake| %>
            <tr>
              <td>
                <div class="btn-group">
                  <%= link_to '編集', edit_menu_intake_path(intake.menu_id, intake.id), class: "btn btn-sm btn-outline-light" %>
                  <%= link_to '削除', menu_intake_path(intake.menu_id, intake.id), method: :delete, class: "btn btn-sm btn-outline-light" %>
                </div>
              </td>
              <td>
                <%= intake.date %>
              </td>
              <td>
                <%= Timing.find(intake.timing_id).name %>
              </td>
              <td>
                <% if @standards.where(menu_id: intake.menu_id) == [] %>
                  <%= intake.menu.title %>                
                <% else %>
                  <%= link_to intake.menu.title, menu_intake_path(intake.menu_id, intake.id), class: "link-text-color td-none" %>
                <% end %>
              </td>
              <td>
                <%= @intake_value = Value.find(intake.value_id).name %>
              </td>
              <td>
                <% if @standards.where(menu_id: intake.menu_id) == [] %>
                ---
                <% else %>
                  <%# 変数の定義 %>
                    <% menu_cal = intake.menu.calorie %>
                    <% menu_amount = intake.menu.amount %>
                    <% standard = @standards.where(menu_id: intake.menu_id) %>    
                    <% stn_large = standard[0].large %>
                    <% stn_medium = standard[0].medium %>
                    <% stn_small = standard[0].small %>
                  <%#// 変数の定義 %>
                    <% if @intake_value == '多め' %>
                      <%= stn_large %>
                    <% elsif @intake_value == '普通' %>
                      <%= stn_medium %>
                    <% elsif @intake_value == '少なめ' %>
                      <%= stn_small %>
                    <% else %>
                      任意の量
                    <% end %>
                  <%= intake.menu.unit %>
                <% end %>
              </td>
              <td>
                <% if @standards.where(menu_id: intake.menu_id) == [] %>
                ---
                <% else %>
                  <% if @intake_value == '多め' %>
                    <%= menu_cal * stn_large / menu_amount %>
                  <% elsif @intake_value == '普通' %>
                    <%= menu_cal * stn_medium / menu_amount %>
                  <% elsif @intake_value == '少なめ' %>
                    <%= menu_cal * stn_small / menu_amount %>
                  <% else %>
                    任意の量
                  <% end %>
                kcal
                <% end %>
              </td>
              <td>
                <% if @standards.where(menu_id: intake.menu_id) == [] %>
                  <%= "*#{intake.menu.title}の基準は登録されていません(計算対象外です)。"%><br>
                  <%= link_to "#{intake.menu.title}の基準を登録する",new_menu_standard_path(intake.menu_id), class:"td-none"%> <br>
                <% end %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
        <%# 日毎のカロリー計算 %>
        <div>
          <h2>一日毎のカロリー合計</h2>
          <% days_ary = [] %>
          <% cals_ary = [] %>
          <% day_cal = 0 %>
          <% one_cal = 0 %>

          <% @intakes.each_with_index do |intake, i| %>
            <% @intake_value = Value.find(intake.value_id).name %>

            <% unless @standards.where(menu_id: intake.menu_id) == [] %>
                <%# 変数の定義 %>
                  <% menu_cal = intake.menu.calorie %>
                  <% menu_amount = intake.menu.amount %>
                  <% standard = @standards.where(menu_id: intake.menu_id) %>    
                  <% stn_large = standard[0].large %>
                  <% stn_medium = standard[0].medium %>
                  <% stn_small = standard[0].small %>
                <%#// 変数の定義 %>
                <%# カロリーの計算 %>
                  <% if @intake_value == '多め' %>
                    <% one_cal = menu_cal * stn_large / menu_amount %>
                  <% elsif @intake_value == '普通' %>
                    <% one_cal = menu_cal * stn_medium / menu_amount %>
                  <% elsif @intake_value == '少なめ' %>
                    <% one_cal = menu_cal * stn_small / menu_amount %>
                  <% else %>
                    任意の量
                  <% end %>
                <%#// カロリーの計算 %>

                <%# ary配列に今回のintakeの日付が入っていない場合 %>
              <% unless days_ary.include?(intake.date) %>
                <%# 一番最初の例外処理 %>
                <% if days_ary == [] %>
                  <% days_ary << intake.date %>
                  <% day_cal = 0 %>
                  <% day_cal += one_cal %>
                <%# //一番最初の例外処理 %>
                <% else %>
                  <% days_ary << intake.date %>
                  <% cals_ary << day_cal %>
                  <% day_cal = 0 %>
                  <% day_cal += one_cal %>
                <% end %>
              <% else %>
                <% day_cal += one_cal %>
              <% end %>
              <%# 一番最後の例外処理 %>
                <% if i == @intakes.length - 1 %>
                  <% cals_ary << day_cal %>
                <% end %>
              <%# //一番最後の例外処理 %>
            <% end %>
          <% end %>

          <%# 日毎のカロリー集計 %>
          <% for num in 0..(days_ary.length - 1)  do %>
            <%= "#{days_ary[num]}: 合計#{cals_ary[num]}kcal "%><br>
          <% end %>
          <%# //日毎のカロリー集計 %>
        </div>
        <%#// 日毎のカロリー計算 %>
    <%# //メイン画面の内容部分 %>
    </main>
  </div>
</div>
<%= render "shared/footer"%>

app/views/intakes/new.html.erb
<%= render "shared/header"%>
<div class="container-fluid">
  <div class="row">
    <%= render "shared/nav-bar"%>
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <%= render "shared/intakes_header" %>
      <%# メイン画面の内容部分 %>
      <h2><%= @menu.title%>の食事実績登録</h2>
      <%= form_with model: [@menu, @intake], local: true, class:"row my-3" do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
        <div class="row my-3 fs-5">
          <div class="col-12">
            <%= f.label :date %>
          </div>
          <div class="col">
            <%= f.date_select :date, start_year: 2021, end_year: 2021 %>
          </div>
        </div>
        <div class="row my-3 fs-5">
          <div class="col-12">        
            <%= f.label :timing_id %>
          </div>
          <div class="col">
            <%= f.collection_select(:timing_id, Timing.all, :id, :name, {}, {}) %>
          </div>
        </div>
        <div class="row my-3 fs-5">
          <div class="col-12">    
            <%= f.label :value_id %>
          </div>
          <div class="col">
            <%= f.collection_select(:value_id, Value.all, :id, :name, {}, {}) %>
          </div>
        </div>
        <div class="d-grid gap-2 col-6 my-4">
          <%= f.submit '登録する', class:"btn btn-primary btn-lg" %>
        </div>
      <% end %>
    </main>
  </div>
</div>
<%= render "shared/footer"%>

app/views/intakes/show.html.erb
<%= render "shared/header"%>
<div class="container-fluid">
  <div class="row">
    <%= render "shared/nav-bar"%>
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <%= render "shared/intakes_header" %>
      <%# メイン画面の内容部分 %>
      <h2>食事実績詳細</h2>
      <div class="table-responsive">
        <table class="table table-sm">
          <thead>
            <tr>
              <th>選択</th>
              <th>日付</th>
              <th>時間帯</th>
              <th>メニュー名</th>
              <th>感覚量</th>
              <th>分量</th>
              <th>カロリー</th>
            </tr>
          </thead>
          <tbody>
          <%# 変数の定義 %>
            <% menu_cal = @intake.menu.calorie %>
            <% menu_amount = @intake.menu.amount %>
            <% standard = @standards.where(menu_id: @intake.menu_id) %>    
            <% stn_large = standard[0].large %>
            <% stn_medium = standard[0].medium %>
            <% stn_small = standard[0].small %>
          <%#// 変数の定義 %>
            <td>
              <div class="btn-group">
                <%= link_to '編集', edit_menu_intake_path(@intake.menu_id, @intake.id), class: "btn btn-sm btn-outline-light" %>
                <%= link_to '削除', menu_intake_path(@intake.menu_id, @intake.id), method: :delete, class: "btn btn-sm btn-outline-light" %>
              </div>
            </td>
            <td>
              <%= @intake.date %>
            </td>
            <td>
              <%= Timing.find(@intake.timing_id).name %>
            </td>
            <td>
              <%= @intake.menu.title %>
            </td>
            <td>
              <%= @intake_value = Value.find(@intake.value_id).name %>
            </td>
            <td>
              <% if @intake_value == '多め' %>
                <%= stn_large %>
              <% elsif @intake_value == '普通' %>
                <%= stn_medium %>
              <% elsif @intake_value == '少なめ' %>
                <%= stn_small %>
              <% else %>
                任意の量
              <% end %>
            g
            </td>
            <td>
              <% if @intake_value == '多め' %>
                <%= menu_cal * stn_large / menu_amount %>
              <% elsif @intake_value == '普通' %>
                <%= menu_cal * stn_medium / menu_amount %>
              <% elsif @intake_value == '少なめ' %>
                <%= menu_cal * stn_small / menu_amount %>
              <% else %>
                任意の量
              <% end %>
            kcal
            </td>
          </tbody>
        </table>
      </div>
    </main>
  </div>
</div>
<%= render "shared/footer"%>

app/views/intakes/update.html.erb
<%= render "shared/header"%>
<div class="container-fluid">
  <div class="row">
    <%= render "shared/nav-bar"%>
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <%= render "shared/intakes_header" %>
      <%# メイン画面の内容部分 %>
      <div><%= @intake.menu.title %>の食事実績が更新されました。</div>
      <div><%= link_to '食事実績へ戻る', intakes_path, class: "btn btn-info my-3" %></div>
    </main>
  </div>
</div>
<%= render "shared/footer"%>